core/urls.py
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "core"

urlpatterns = [

    path('', home, name='home'),
    path('artists', ArtistListView.as_view(), name='artists'),
    path('artists/<slug:slug>', ArtistDetailView.as_view(), name='artist-details'),
    path('genres', GenreListView.as_view(), name='genres'),
    path('genres/<int:pk>', SongsByGenreListView.as_view(), name='songs-by-genre'),
    path('songs/', include([
        path('make-favorite', favoriteunfavorite, name='song-favorite'),
        path('<str:audio_id>', SongDetailsView.as_view(), name='song-detail'), 
        path('record-playback', record_playback, name='record-playback'),
        path('upload', SongUploadView.as_view(), name='upload'),
        path('<slug:audio_id>', SongDetailsView.as_view(), name='upload-details'),
    ])),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),

    # API Urls
    path('v1/api/', include([
        path('', include('core.api.urls')),
        path('accounts/', include('accounts.api.urls')),
    ])),
]

templates/songs/create.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block stylesheets %}

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
    <link href="{% static 'css/select2-bootstrap4.min.css' %}" rel="stylesheet"/>

    <style>
        .lds-ellipsis {
            display: inline-block;
            position: relative;
            width: 64px;
            height: 64px;
        }

        .lds-ellipsis div {
            position: absolute;
            top: 27px;
            width: 11px;
            height: 11px;
            border-radius: 50%;
            background: #921bb3;
            animation-timing-function: cubic-bezier(0, 1, 1, 0);
        }

        .lds-ellipsis div:nth-child(1) {
            left: 6px;
            animation: lds-ellipsis1 0.6s infinite;
        }

        .lds-ellipsis div:nth-child(2) {
            left: 6px;
            animation: lds-ellipsis2 0.6s infinite;
        }

        .lds-ellipsis div:nth-child(3) {
            left: 26px;
            animation: lds-ellipsis2 0.6s infinite;
        }

        .lds-ellipsis div:nth-child(4) {
            left: 45px;
            animation: lds-ellipsis3 0.6s infinite;
        }

        @keyframes lds-ellipsis1 {
            0% {
                transform: scale(0);
            }
            100% {
                transform: scale(1);
            }
        }

        @keyframes lds-ellipsis3 {
            0% {
                transform: scale(1);
            }
            100% {
                transform: scale(0);
            }
        }

        @keyframes lds-ellipsis2 {
            0% {
                transform: translate(0, 0);
            }
            100% {
                transform: translate(19px, 0);
            }
        }

        .upload-image svg {
            width: 55px;
            height: 55px;
        }

        .upload-image {
            display: flex;
            align-items: center;
            justify-content: center;
            width: 260px;
            height: 260px;
            background-color: rgba(0, 0, 0, 0.06);
            color: #4b4b4b;
            border-radius: 5px;
            overflow: hidden;
            border: 2px dashed #cdcdcd;
        }
    </style>


{% endblock %}

{% block content %}

    <main id="pageWrapper">
        <div class="banner bg-song"></div>
        <div class="main-container">
            <div class="row section">
                <div class="col-xl-10 col-md-12 mx-auto">
                    <div class="card">
                        <form action="{% url 'core:upload' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="card-header">
                                <h6 class="card-title mb-0">Add Music</h6>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6 col-xl-4">
                                        <div class="upload-image">
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                                <path fill="currentColor"
                                                      d="M5,3A2,2 0 0,0 3,5V19A2,2 0 0,0 5,21H14.09C14.03,20.67 14,20.34 14,20C14,19.32 14.12,18.64 14.35,18H5L8.5,13.5L11,16.5L14.5,12L16.73,14.97C17.7,14.34 18.84,14 20,14C20.34,14 20.67,14.03 21,14.09V5C21,3.89 20.1,3 19,3H5M19,16V19H16V21H19V24H21V21H24V19H21V16H19Z"></path>
                                            </svg>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-xl-8">
                                        <div class="form-row form-group">
                                            <label for="songFile" class="col-md-4 text-md-right col-form-label">Song
                                                File</label>
                                            <div class="col-md-7">
                                                <div class="custom-file">
                                                    <input type="file" name="song" class="custom-file-input" id="songFile" accept=".mp3,audio/*" required>
                                                    <label class="custom-file-label" for="songFile" id="songChoose">Choose file</label>
                                                    <span role="alert" style="color: #8c8e90; font-size: 10px">
                                                        <strong>Max file size is 10MB</strong>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-row form-group">
                                            <label for="songName" class="col-md-4 text-md-right col-form-label">Song Name</label>
                                            <div class="col-md-7">
                                                <input type="text" name="title" id="songName" class="form-control" required value="">
                                            </div>
                                        </div>
                                        <div class="form-row form-group">
                                            <label for="songImage" class="col-md-4 text-md-right col-form-label">Song Cover Image</label>
                                            <div class="col-md-7">
                                                <div class="custom-file">
                                                    <input type="file" name="thumbnail" class="custom-file-input"
                                                           id="songImage" required>
                                                    <label class="custom-file-label" for="songImage">Choose file</label>
                                                    <span role="alert" style="color: #8c8e90; font-size: 10px">
                                                        <strong>Max file size is 2MB</strong>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-row form-group">
                                            <label for="description" class="col-md-4 text-md-right col-form-label">Description</label>
                                            <div class="col-md-7">
                                                <textarea name="description" id="description" class="form-control"
                                                          required rows="5"></textarea>
                                            </div>
                                        </div>
                                        <div class="form-row form-group">
                                            <label for="artistName" class="col-md-4 text-md-right col-form-label">Artist Name</label>
                                            <div class="col-md-7">
                                                <select name="artists[]" class="select2 form-control" multiple="multiple" id="artistName">
                                                    <option></option>
                                                    {% for artist in artists %}
                                                        <option value="{{ artist.id }}">{{ artist.name }}</option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-row form-group">
                                            <label for="genre"
                                                   class="col-md-4 text-md-right col-form-label">Genre</label>
                                            <div class="col-md-7">
                                                <select name="genre" id="genre" class="form-control" required>
                                                    <option value="" selected disabled>Select Genre</option>
                                                    {% for genre in genres %}
                                                        <option value="{{ genre.id }}">{{ genre.name }}</option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <div class="row">
                                    <div class="col-md-6 offset-5">
                                        <div class="lds-ellipsis" style="display: none;">
                                            <div></div>
                                            <div></div>
                                            <div></div>
                                            <div></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-5"></div>
                                    <div class="col-md-7">
                                        <button type="submit" class="btn btn-brand btn-air">Save Song</button>
                                        <button type="reset" class="btn btn-outline-secondary">Clear Form</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% include 'includes/footer.html' %}
    </main>

{% endblock %}

{% block javascripts %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script type="text/javascript">

        let select2 = $(".select2");

        select2.select2({
            placeholder: "Select artists",
            theme: 'bootstrap4',
            width: 'style',
            tags: true,
        });

        select2.on('select2:select', function (e) {
            let elm = e.params.data.element;
            $elm = jQuery(elm);
            $t = jQuery(this);
            $t.append($elm);
            $t.trigger('change.select2');
        });

        $('#songImage').change(function () {
            if (this.files && this.files[0]) {
                let reader = new FileReader();

                reader.onload = function (e) {
                    $('.upload-image svg').remove();
                    $('.upload-image img').remove();
                    $('.upload-image').prepend('<img src="' + e.target.result + '" alt="" style="width: 100%"/>');
                };
                reader.readAsDataURL(this.files[0]);
            }
        });

        function _(el) {
            return document.getElementById(el);
        }

        let form = $('form');

        form.submit(function (e) {
            e.preventDefault();

            $(this).find('button[type=submit]').attr('disabled', true);
            $(this).find('.lds-ellipsis').css('display', "block");

            $.ajax({
                url: $(this).attr('action'),
                type: 'post',
                datatype: 'json',
                data: new FormData(this),
                contentType: false,
                processData: false,
                success: function (data) {
                    form.find('button[type=submit]').attr('disabled', false);
                    form.find('.lds-ellipsis').css('display', "none");

                    if (data.status === 'validation' || data.status === 'error') {
                        $.each(data.message, function (index, message) {
                            toastr.warning(message);
                        });
                        toastr.options = {
                            "positionClass": "toast-bottom-right",
                            "timeOut ": 30,
                        };
                    } else if (data.status === true) {

                        toastr.options = {
                            "positionClass": "toast-bottom-right",
                        };
                        toastr.success(data.message);

                        setTimeout(function () {
                            window.location.href = data.redirect;
                        }, 2000);
                    }
                }, error: function (err) {
                    console.log(err.data);
                    form.find('.lds-ellipsis').css('display', "none");
                    form.find('button[type=submit]').attr('disabled', false);
                }
            });
        })
    </script>

{% endblock %}

templates/songs/show.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load is_favorited %}

{% block content %}

    <main id="pageWrapper">
        <div class="banner bg-song"></div>
        <div class="main-container">
            <div class="row section text-center text-md-left">
                <div class="col-xl-3 col-lg-4 col-sm-5">
                    <img src="{{ song.thumbnail.url }}" alt="" class="card-img--radius-lg">
                </div>
                <div class="col-xl-9 col-lg-8 col-sm-7">
                    <div class="row pt-4">
                        <div class="col-xl-8 col-lg-6">
                            <h5>{{ song.title }}</h5>
                            <p>{{ song.artists.0.name }}</p>
                            <div class="text-warning stars">
                                <i class="la la-star"></i>
                                <i class="la la-star"></i>
                                <i class="la la-star"></i>
                                <i class="la la-star"></i>
                                <i class="la la-star-half-empty"></i>
                            </div>
                            <div class="mt-4">
                                <a href="javascript:void(0);"
                                   class="btn btn-pill btn-air btn-bold btn-danger"
                                   id="play-pause"
                                   data-audio='{"name": "{{ song.title }}", "artist": "{{ song.artists.0.name }}", "album": "", "url": "{{ song.song.url }}", "cover_art_url": "{{ song.thumbnail.url }}"}'>
                                    Play
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-4 col-lg-6">
                            <div class="pt-3 pt-lg-0 text-lg-right">
                                {% is_favorited song request.user as favorited %}
                                <button class="btn btn-pill btn-air btn-danger btn-icon-only" id="btn-favorite"
                                        data-decision="{{ favorited }}" data-url="{% url 'core:song-favorite' %}"
                                        data-song-id="{{ song.id }}" data-user="{{ request.user }}">
                                    {% if favorited == 'remove' and request.user.is_authenticated %}
                                        <i class="la la-heart"></i>
                                    {% else %}
                                        <i class="la la-heart-o"></i>
                                    {% endif %}
                                </button>
                                <button class="btn btn-pill btn-air btn-warning btn-icon-only" id="btn-playlist">
                                    <i class="la la-plus"></i>
                                </button>
                                <a class="btn btn-pill btn-air btn-success btn-icon-only" href="#">
                                    <i class="la la-download" style="margin-top: 10px; color: #fff"></i>
                                </a>
                                <button class="btn btn-pill btn-air btn-brand btn-icon-only" data-toggle="modal"
                                        data-target="#shareModal">
                                    <i class="la la-share-alt"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section"> 
                <h2>You Might Also Like</h2>
                <div class="row recommended-music"> 
                    {% for rec_song in recommended_songs %}
                        <div class="col-md-3"> 
                            <a href="{% url 'core:song-detail' audio_id=rec_song.audio_id  %}">
                                <img src="{{ rec_song.thumbnail.url }}" alt="{{ rec_song.title }}" class="img-fluid">
                            </a>
                            <p class="song-title">{{ rec_song.title }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="section">
                <div id="waveform-load"></div>
                <div id="waveform"></div>
            </div>
        </div>
        {% include 'includes/footer.html' %}
    </main>

{% endblock %}

{% block javascripts %}

    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/amplitudejs@5.0.2/dist/amplitude.min.js"></script>
    <script src="{% static 'js/wavesurfer.min.js' %}"></script>
    <script type="text/javascript">


        $("#play-pause").click(function () {
            var user = "{{ request.user.is_authenticated }}";
            if (user !== "True") {
                alert("Please login to play songs.");
                return;
            }

            var songId = "{{ song.id }}"; 
            var csrfToken = $("input[name='csrfmiddlewaretoken']").val(); 
            var recordPlaybackUrl = "{% url 'core:record-playback' %}"; 

            $.ajax({
                type: 'POST',
                url: recordPlaybackUrl,
                data: {
                    'csrfmiddlewaretoken': csrfToken,
                    'song_id': songId,
                },
                success: function (response) {
                    console.log(response.message);
                },
                error: function (error) {
                    console.log(error);
                }
            });
        });
        
        
        let favorite_btn = $('#btn-favorite');

        favorite_btn.on('click', function () {
            let user = $(this).data('user');

            if (user) {

                let song_id = $(this).data('song-id');
                let decision = $(this).data('decision');

                $.ajaxSetup({
                    headers: {
                        'X-CSRFToken': csrfmiddlewaretoken
                    }
                });

                $.ajax({
                    type: 'POST',
                    url: $(this).data('url'),
                    data: {
                        song_id,
                        decision,
                    },
                    dataType: 'json',
                    success: function (res) {
                        if (res.status === true) {
                            if (decision === 'make') {
                                favorite_btn.attr('data-decision', 'remove');
                                favorite_btn.find('i.la-heart-o').removeClass('la-heart-o').addClass('la-heart');
                            } else {
                                favorite_btn.attr('data-decision', 'make');
                                favorite_btn.find('i.la-heart').removeClass('la-heart').addClass('la-heart-o');
                            }
                            toastr.options = {
                                "positionClass": "toast-bottom-right",
                            };
                            toastr.success(res.message);
                        }
                    },
                    error: function (err) {
                        console.log(err);
                    }
                });
            } else {
                toastr.options = {
                    "positionClass": "toast-bottom-right",
                };
                toastr.warning('Please login to continue');
            }
        });

        Amplitude.init({
            "songs": [{
                name: "{{ song.title }}",
                artist: "{{ song.artists }}",
                album: "Mummy",
                url: "{{ song.song.url }}",
                cover_art_url: "{{ song.thumbnail.url }}"
            }],
            "bindings": {
                32: 'play_pause'
            },
            "callbacks": {
                'play': function () {
                    wavesurfer.play();
                    wavesurfer.setCurrentTime(Amplitude.getSongPlayedSeconds());
                },
                'timeupdate': function () {
                    wavesurfer.setCurrentTime(Amplitude.getSongPlayedSeconds());
                },
                'seeked': function () {
                    wavesurfer.setCurrentTime(Amplitude.getSongPlayedSeconds());
                },
                'pause': function () {
                    wavesurfer.setCurrentTime(Amplitude.getSongPlayedSeconds());
                    wavesurfer.pause();
                }
            }
        });

        window.onkeydown = function (e) {
            return !(e.keyCode === 32);
        };

        document.getElementById('song-played-progress').addEventListener('click', function (e) {
            let offset = this.getBoundingClientRect();
            let x = e.pageX - offset.left;

            Amplitude.setSongPlayedPercentage((parseFloat(x) / parseFloat(this.offsetWidth)) * 100);
        });

        let wavesurfer = WaveSurfer.create({
            container: '#waveform',
            waveColor: '#733ce6',
            progressColor: '#bfbfbf',
            height: 150,
            scrollParent: false,
            responsive: true,
        });

        wavesurfer.on('loading', function (integer) {
            $('#waveform-load').html("Generating waves.. (" + integer + '%)');
        });

        wavesurfer.on('ready', function (percents) {
            wavesurfer.setVolume(0);
            $('#waveform-load').empty();
        });

        $("a[data-audio]").on("click", function () {
            $('#audioPlayer').css('visibility', 'visible');
            if ($(this).text().trim() === 'Play') {
                $('.amplitude-play-pause').addClass('amplitude-playing').removeClass('amplitude-paused');
                $(this).text('Pause');
            } else {
                $('.amplitude-play-pause').removeClass('amplitude-playing').addClass('amplitude-paused');
                $(this).text('Play');
            }

            if ($('.amplitude-play-pause').hasClass('amplitude-playing')) {
                Amplitude.play();
            } else {
                Amplitude.pause();
            }
        });

        wavesurfer.on('seek', function (seeks) {
        });

        wavesurfer.load('{{ song.song.url }}');

        $('.amplitude-play-pause').on('click', function () {
            if ($(this).hasClass('amplitude-playing')) {
                Amplitude.play();
                $('#play-pause').text('Pause');
            } else {
                Amplitude.pause();
                $('#play-pause').text('Play');
            }
        });

        let volumeIconClick = function () {

            $(document).on("click", ".volume-dropdown-menu", function (s) {
                s.stopPropagation();
            });

            let s = $('.audio-volume input[type="range"]'), t = $(".audio-volume .btn");
            s.on("change", function () {
                let s = $(this), e = parseInt(s.val(), 10);
                0 === e ? t.html('<i class="ion-md-volume-mute"></i>') : e > 0 && e < 70 ? t.html('<i class="ion-md-volume-low"></i>') : e > 70 && t.html('<i class="ion-md-volume-high"></i>')
            })
        };

        volumeIconClick();
    </script>

{% endblock %}